DROP TABLE IF EXISTS FAQ;
DROP TABLE IF EXISTS SHOWCASE;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS ORDER_PRODUCT;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS ARTICLE;
DROP TABLE IF EXISTS CAROUSEL;
DROP TABLE IF EXISTS IMAGE;
DROP TABLE IF EXISTS RESET_PASSWORD;
DROP TABLE IF EXISTS VALIDATION;
DROP TABLE IF EXISTS USERS;
-- Create

CREATE TABLE USERS (
    id_user SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    newsletter BOOLEAN NOT NULL DEFAULT FALSE,
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_admin BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE VALIDATION (
    id_validation SERIAL PRIMARY KEY,
    id_user INT NOT NULL,
    valid_exp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 DAY',
    FOREIGN KEY (id_user) REFERENCES USERS(id_user)
);

CREATE TABLE RESET_PASSWORD (
    id_reset SERIAL PRIMARY KEY,
    id_user INT NOT NULL,
    rst_tkn VARCHAR(50) NOT NULL,
    rst_tkn_exp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 DAY',
    FOREIGN KEY (id_user) REFERENCES USERS(id_user)
);

CREATE TABLE IMAGE (
    id_img SERIAL PRIMARY KEY,
    img_name VARCHAR(50) NOT NULL,
    img_path VARCHAR(50) NOT NULL
);

CREATE TABLE CAROUSEL (
    id_car SERIAL PRIMARY KEY,
    id_img INT NOT NULL,
    link_car VARCHAR(50) NOT NULL,
    FOREIGN KEY (id_img) REFERENCES IMAGE(id_img)
);

CREATE TABLE ARTICLE(
    id_art SERIAL PRIMARY KEY,
    id_img INT NOT NULL,
    art_title VARCHAR(50) NOT NULL,
    art_text TEXT NOT NULL,
    art_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_img) REFERENCES IMAGE(id_img)
);

CREATE TABLE ORDERS (
    id_order SERIAL PRIMARY KEY,
    id_user INT NOT NULL,
    order_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_user) REFERENCES USERS(id_user)
);

CREATE TABLE PRODUCT (
    id_prod SERIAL PRIMARY KEY,
    p_name VARCHAR(50) NOT NULL,
    p_price FLOAT NOT NULL,
    description TEXT NOT NULL,
    id_img INT NOT NULL,
    on_sale BOOLEAN NOT NULL DEFAULT FALSE,
    is_star BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (id_img) REFERENCES IMAGE(id_img)
);

CREATE TABLE ORDER_PRODUCT (
    id_order INT NOT NULL,
    id_prod INT NOT NULL,
    quantity INT NOT NULL,
    FOREIGN KEY (id_order) REFERENCES ORDERS(id_order),
    FOREIGN KEY (id_prod) REFERENCES PRODUCT(id_prod)
);

CREATE TABLE CART (
    id_cart SERIAL PRIMARY KEY,
    id_user INT NOT NULL,
    id_prod INT NOT NULL,
    quantity INT NOT NULL,
    FOREIGN KEY (id_user) REFERENCES USERS(id_user),
    FOREIGN KEY (id_prod) REFERENCES PRODUCT(id_prod)
);

CREATE TABLE CATEGORY (
    id_cat SERIAL PRIMARY KEY,
    cat_name VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCT_CATEGORY (
    id_prod INT NOT NULL,
    id_cat INT NOT NULL,
    FOREIGN KEY (id_prod) REFERENCES PRODUCT(id_prod),
    FOREIGN KEY (id_cat) REFERENCES CATEGORY(id_cat)
);

CREATE TABLE SHOWCASE (
    id_show SERIAL PRIMARY KEY,
    id_cat INT NOT NULL,
    FOREIGN KEY (id_cat) REFERENCES CATEGORY(id_cat)
);

CREATE TABLE FAQ (
    id_faq SERIAL PRIMARY KEY,
    question VARCHAR(50) NOT NULL,
    answer TEXT NOT NULL
);